name: Docs Build & Deploy
on:
  push:
    branches:
      - "master"
jobs:
  build-and-deploy:
    name: Publish Docs ğŸ¦–
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Deploy ğŸš€
        run: | # Install npm packages and Deploy the Storybook files
          git checkout gh-pages && git rebase master
          cd ./docs
          yarn install
          yarn build
          git push origin gh-pages
