name: Storybook Build & Deploy
on:
  push:
    branches:
      - "master"
jobs:
  build-and-deploy:
    name: Publish Master Storybook ğŸ“•
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Deploy ğŸš€
        run: | # Install npm packages and Deploy the Storybook files
          yarn install
          yarn run deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
